import streamlit as st
from datetime import date

st.set_page_config(page_title="LegalEase AI", page_icon="⚖️")
st.title("⚖️ LegalEase AI")
st.write("AI-Powered Legal Contract Generator")

doc = st.selectbox("Document Type", ["Freelance Contract", "NDA", "Employment"])
details = st.text_area("Enter Details", "Freelance contract for web developer, client TechNova Inc, 3 months, 50000 rupees", height=120)

if st.button("Generate Contract", type="primary"):
    if details:
        today = date.today().strftime('%B %d, %Y')
        st.success("✅ Contract Generated!")
        st.markdown(f"""
        # FREELANCE SERVICES AGREEMENT
        *Date:* {today}
        
        *1. Client:* TechNova Inc
        *2. Developer:* Jane Doe
        *3. Project:* {details}
        
        *4. Payment:* Rs. 50,000 - 50% advance, 50% on delivery
        *5. Duration:* 3 Months
        *6. Terms:* Confidential, Work for Hire, No NDA violation
        
        *Signatures:*
        Developer: _______
        Client: _______
        
        ---
        Generated by LegalEase AI
        """)
        st.balloons()
    else:
        st.warning("Please enter details da!")
